/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum170625;

/**
 *
 * @author Ari
 */
public class MenuMinuman extends javax.swing.JFrame {

    private MenuUtama utama;
    /**
     * Creates new form c
     */
    public MenuMinuman() {
        initComponents();
    }
    
    public MenuMinuman(MenuUtama utama){
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkTeh = new javax.swing.JCheckBox();
        cbMangga = new javax.swing.JComboBox<>();
        chkKopi = new javax.swing.JCheckBox();
        txtTotTeh = new javax.swing.JTextField();
        chkAlpukat = new javax.swing.JCheckBox();
        txtTotKopi = new javax.swing.JTextField();
        chkMangga = new javax.swing.JCheckBox();
        txtTotAlpukat = new javax.swing.JTextField();
        txtTeh = new javax.swing.JTextField();
        txtTotMangga = new javax.swing.JTextField();
        txtKopi = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        txtAlpukat = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtMangga = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        cbTeh = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbKopi = new javax.swing.JComboBox<>();
        cbAlpukat = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chkTeh.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        chkTeh.setForeground(new java.awt.Color(102, 153, 0));
        chkTeh.setText("Teh");
        chkTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTehActionPerformed(evt);
            }
        });

        cbMangga.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        cbMangga.setForeground(new java.awt.Color(102, 102, 0));
        cbMangga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMangga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbManggaActionPerformed(evt);
            }
        });

        chkKopi.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        chkKopi.setForeground(new java.awt.Color(102, 153, 0));
        chkKopi.setText("Kopi ");
        chkKopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKopiActionPerformed(evt);
            }
        });

        txtTotTeh.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        txtTotTeh.setText("0");

        chkAlpukat.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        chkAlpukat.setForeground(new java.awt.Color(102, 153, 0));
        chkAlpukat.setText("Jus Alpukat");
        chkAlpukat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAlpukatActionPerformed(evt);
            }
        });

        txtTotKopi.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        txtTotKopi.setText("0");

        chkMangga.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        chkMangga.setForeground(new java.awt.Color(102, 153, 0));
        chkMangga.setText("Jus Mangga");
        chkMangga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkManggaActionPerformed(evt);
            }
        });

        txtTotAlpukat.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        txtTotAlpukat.setText("0");

        txtTeh.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        txtTeh.setText("0");

        txtTotMangga.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        txtTotMangga.setText("0");

        txtKopi.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        txtKopi.setText("0");

        btnTotal.setBackground(new java.awt.Color(51, 0, 51));
        btnTotal.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnTotal.setForeground(new java.awt.Color(255, 102, 0));
        btnTotal.setText("TOTAL");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        txtAlpukat.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        txtAlpukat.setText("0");
        txtAlpukat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlpukatActionPerformed(evt);
            }
        });

        txtTotal.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        txtTotal.setText("0");
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        txtMangga.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        txtMangga.setText("0");
        txtMangga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManggaActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(51, 0, 51));
        btnKembali.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 102, 0));
        btnKembali.setText("Kembali Ke Menu Utama");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        cbTeh.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        cbTeh.setForeground(new java.awt.Color(102, 102, 0));
        cbTeh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTehActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("MENU MINUMAN");

        cbKopi.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        cbKopi.setForeground(new java.awt.Color(102, 102, 0));
        cbKopi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbKopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKopiActionPerformed(evt);
            }
        });

        cbAlpukat.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        cbAlpukat.setForeground(new java.awt.Color(102, 102, 0));
        cbAlpukat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbAlpukat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlpukatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTotal)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAlpukat)
                            .addComponent(chkMangga)
                            .addComponent(chkKopi, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkTeh))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(txtTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKopi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlpukat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMangga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAlpukat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMangga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtTotKopi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(271, 271, 271))
                        .addComponent(txtTotAlpukat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(txtTotMangga, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTotTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(271, 271, 271))
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTeh)
                    .addComponent(txtTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkKopi)
                    .addComponent(txtKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAlpukat)
                    .addComponent(txtAlpukat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAlpukat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotAlpukat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMangga)
                    .addComponent(txtMangga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMangga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotMangga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnKembali)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAlpukatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlpukatActionPerformed
        int jml = (int)cbAlpukat.getSelectedIndex();
        double harga = Double.parseDouble(txtAlpukat.getText());
        double total = jml * harga;
        txtTotAlpukat.setText(Double.toString(total));
    }//GEN-LAST:event_cbAlpukatActionPerformed

    private void cbKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKopiActionPerformed
        int jml = (int)cbKopi.getSelectedIndex();
        double harga = Double.parseDouble(txtKopi.getText());
        double total = jml * harga;
        txtTotKopi.setText(Double.toString(total));
    }//GEN-LAST:event_cbKopiActionPerformed

    private void chkManggaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkManggaActionPerformed
        txtMangga.setText("8000");
    }//GEN-LAST:event_chkManggaActionPerformed

    private void cbTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTehActionPerformed
        int jml = (int)cbTeh.getSelectedIndex();
        double harga = Double.parseDouble(txtTeh.getText());
        double total = jml * harga;
        txtTotTeh.setText(Double.toString(total));
    }//GEN-LAST:event_cbTehActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotal.getText();
        if(utama !=null){
            utama.setTotalMakanan(total);
            utama.setVisible(true);
        }
        this.dispose(); //menutup jendela form menu makanan
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void chkAlpukatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAlpukatActionPerformed
        txtAlpukat.setText("23000");
    }//GEN-LAST:event_chkAlpukatActionPerformed

    private void txtManggaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManggaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManggaActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void chkKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKopiActionPerformed
        txtKopi.setText("15000");
    }//GEN-LAST:event_chkKopiActionPerformed

    private void txtAlpukatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlpukatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlpukatActionPerformed

    private void cbManggaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbManggaActionPerformed
        int jml = (int)cbMangga.getSelectedIndex();
        double harga = Double.parseDouble(txtMangga.getText());
        double total = jml * harga;
        txtTotMangga.setText(Double.toString(total));
    }//GEN-LAST:event_cbManggaActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double nasgor = Double.parseDouble(txtTotTeh.getText());
        double miegor = Double.parseDouble(txtTotKopi.getText());
        double sate = Double.parseDouble(txtTotAlpukat.getText());
        double soto = Double.parseDouble(txtTotMangga.getText());

        double total = nasgor + miegor + sate + soto;
        txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void chkTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTehActionPerformed
        txtTeh.setText("25000");
    }//GEN-LAST:event_chkTehActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbAlpukat;
    private javax.swing.JComboBox<String> cbKopi;
    private javax.swing.JComboBox<String> cbMangga;
    private javax.swing.JComboBox<String> cbTeh;
    private javax.swing.JCheckBox chkAlpukat;
    private javax.swing.JCheckBox chkKopi;
    private javax.swing.JCheckBox chkMangga;
    private javax.swing.JCheckBox chkTeh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAlpukat;
    private javax.swing.JTextField txtKopi;
    private javax.swing.JTextField txtMangga;
    private javax.swing.JTextField txtTeh;
    private javax.swing.JTextField txtTotAlpukat;
    private javax.swing.JTextField txtTotKopi;
    private javax.swing.JTextField txtTotMangga;
    private javax.swing.JTextField txtTotTeh;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
